#!/bin/bash

# Käyttö:  rpi-clone-setup {-t|--test} hostname
#    esim:  sudo rpi-clone-setup bozo
#
# rpi-cone ajaa automaattisesti tämän skriptin (kun on annettu -s optio)
# asettaakseem vaihtoehtoisen host namen. Kloonattu järjestelmä mountataan
# hakemistoon /mnt/clone, jos ei tehtä testi valinnalla -t.
#
# Tai scripti voidaan ajaa käsin kloonaamisen loputtua, kun rpi-cloe
# pitää tauon ja kloonattu tiedostojärjestelmä on edelleen mountattuna
# hakemistossa /mn/clone.
#
# Tai scriptin voi ajaa käsin valitsimella -t, jolloin tiedostot käsitellään
# testihakemistoon /tmp/clone-test. Aja -t nähdäksesi onko tietostot käsitelty
# oikein.
#   esim:  sudo rpi-clone-setup -t bozo
#
# Tämä on käynnistysscripti joka käsittelee vain tiedostoja /etc/hosts ja
# /etc/hostsname. Varmista, että sccripti työskentelee oikein /etc/hosts
# tiedostosi kanssa.
#
# If adding a customization for another file:
#    Add the file to file_list.
#    If needed, add a mkdir -p line to the "if ((testing))" part.
#    Add the scripting necessary to customize the file.
#    Test new scripting by running:  rpi-clone-setup -t newhostname
#

file_list="etc/hostname etc/hosts"

clone=/mnt/clone
clone_test=/tmp/clone-test

PGM=`basename $0`

if [ `id -u` != 0 ]
then
	echo "Sinun täytyy olla root ajaaksesi $PGM"
	exit 0
fi

function usage
	{
	echo "Käyttö: $PGM hostname  {-t|--test}"
	echo "   Esim:  $PGM rpi1"
	echo "   Muokkaa tiedostoja tarpeen mukaan asettaaksesi uuden hostin."
	echo "   Käsitellyt tiedostot ovat:"
	for file in $file_list
	do
		echo "        $file"
	done
	echo ""
	echo "Jos testaat (-t lippu) niin tiedostot on kopioitu ja käsitelty hakemistoon $clone_test"
	echo ""
	exit 0
	}

testing=0
while [ "$1" ]
do
	case "$1" in
		-t|--test)
			testing=1
			;;
		*)
			if [ "$newhost" != "" ]
			then
				echo "Väärät argumentit"
				usage
			fi
			newhost=$1
			;;
	esac
	shift
done

if [ "$newhost" = "" ]
then
	echo -e "Sinun täytyy antaa kohteen hostname\n"
	usage
fi

echo -e "\t$newhost\t- target hostname"

if ((!testing)) && [ ! -d /mnt/clone/etc ]
then
	echo "Kohteena olevaa kloonattua tiedostojärjestelmää ei saatu mountattua hakemistoon /mnt/clone"
	echo "Keskeytetään!"
	exit 0
fi

if ((testing))
then
	cd /tmp
	rm -rf $clone_test
	clone=$clone_test

	mkdir -p $clone/etc

	echo "**********************************************"
	echo "Testiasetukset: kopioidaan tiedostot hakemistoon $clone"
	for file in $file_list
	do
		echo "    cp /$file $clone/$file"
		cp /$file $clone/$file
	done
	echo "Testiajo muokkaa noita tiedostoja."
	echo "**********************************************"
	echo ""
fi


##
# Set /etc/hostname
#
cd $clone/etc
echo $newhost > hostname
#
# Read it back to verify.
#
echo "$clone/etc/hostname - set new hostname: "
LINE=`cat hostname`
echo -e "$LINE\n"


##
# Edit /etc/hosts - edit the sed command if editing fails for your /etc/hosts.
#
cd $clone/etc
sed -i s/"$HOSTNAME"/"$newhost"/ hosts
#
# Read it back to verify.
#
echo "$clone/etc/hosts - asettaa uuden hostnamen \"$newhost\" riveille: "
LINE=`grep $newhost hosts`
echo -e "$LINE\n"


##
# Voit lisätä enemmän kustomointeja, jos haluat.
#


exit 0

